[book]
authors = ["npmstudy"]
language = "en"
multilingual = false
src = "src"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
additional-css = ["custom.css"]
git-repository-url = "https://github.com/npmstudy/Your-First-Node.js-with-TypeScript-Course"